config/routes.rb
Rails.application.routes.draw do
  root 'restaurantes#index'

  resources :restaurantes
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurantes_controller.rb
class RestaurantesController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def read
  end

  def update
  end

  def delete
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurantes_helper.rb
module RestaurantesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Melp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/restaurantes/create.html.erb
<h1>Restaurantes#create</h1>
<p>Find me in app/views/restaurantes/create.html.erb</p>

app/views/restaurantes/delete.html.erb
<h1>Restaurantes#delete</h1>
<p>Find me in app/views/restaurantes/delete.html.erb</p>

app/views/restaurantes/index.html.erb
<div class="container">
	<h1 class="text-center">Restaurants App</h1>
	<br><br><br>
	<%= link_to "Add New Restaurant", new_restaurante_path, class: "btn btn-success float-right" %>
	<br><br><br>
	<table class="table">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Rating</th>
      <th scope="col">Name</th>
      <th scope="col">Site</th>
      <th scope="col">Email</th>
      <th scope="col">Phone</th>
      <th scope="col">Street</th>
      <th scope="col">City</th>
      <th scope="col">State</th>
      <th scope="col">Lat</th>
      <th scope="col">Long</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>Mark</td>
      <td>Otto</td>
      <td>@mdo</td>
    </tr>
  </tbody>
</table>
</div>

app/views/restaurantes/new.html.erb
<br><br><br>

<div class="container">
	<div class="card">
	  <h5 class="card-header text-center">Create a new Restaurant</h5>
	  <div class="card-body">
	    <form>
		  <div class="form-group">
		    <label for="exampleInputEmail1">Email address</label>
		    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
		    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
		  </div>
		  <div class="form-group">
		    <label for="exampleInputPassword1">Password</label>
		    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
		  </div>
		  <div class="form-check">
		    <input type="checkbox" class="form-check-input" id="exampleCheck1">
		    <label class="form-check-label" for="exampleCheck1">Check me out</label>
		  </div>
		  <button type="submit" class="btn btn-primary">Submit</button>
		</form>
	  </div>
	</div>
</div>	

app/views/restaurantes/read.html.erb
<h1>Restaurantes#read</h1>
<p>Find me in app/views/restaurantes/read.html.erb</p>

app/views/restaurantes/update.html.erb
<h1>Restaurantes#update</h1>
<p>Find me in app/views/restaurantes/update.html.erb</p>